export const nepalLocations: Record<string, string[]> = {
  "Achham": ["Mangalsen", "Kamalbazar", "Sanphebagar", "Panchadewal Binayak"],
  "Arghakhanchi": ["Sandhikharka", "Sitganga", "Bhumikasthan"],
  "Baglung": ["Baglung", "Dhorpatan", "Galkot", "Jaimini"],
  "Baitadi": ["Dasharathchand", "Patan", "Melauli", "Purchaudi"],
  "Bajhang": ["Jaya Prithvi", "Bungal"],
  "Bajura": ["Badimalika", "Triveni", "Budhiganga", "Budhinanda"],
  "Banke": ["Nepalgunj", "Kohalpur"],
  "Bara": ["Kalaiya", "Jitpur Simara", "Kolhabi", "Nijgadh", "Mahagadhimai", "Pacharauta"],
  "Bardiya": ["Gulariya", "Rajapur", "Madhuwan", "Thakurbaba", "Basgadhi", "Barbardiya"],
  "Bhaktapur": ["Bhaktapur", "Madhyapur Thimi", "Suryabinayak", "Changunarayan"],
  "Bhojpur": ["Bhojpur", "Shadanand"],
  "Chitwan": ["Bharatpur", "Ratnanagar", "Khairahani", "Rapti", "Kalika", "Madi"],
  "Dadeldhura": ["Amargadhi", "Parshuram"],
  "Dailekh": ["Narayan", "Dullu", "Chamunda Bindrasaini", "Aathbis"],
  "Dang": ["Ghorahi", "Tulsipur", "Lamahi"],
  "Darchula": ["Mahakali", "Shailyashikhar"],
  "Dhading": ["Nilkantha", "Dhunibeshi"],
  "Dhankuta": ["Dhankuta", "Pakhribas", "Mahalaxmi"],
  "Dhanusha": ["Janakpur", "Chhireshwarnath", "Ganeshman Charnath", "Dhanusadham", "Nagarain", "Bideha", "Mithila", "Sahidnagar", "Sabaila", "Kamala", "Hansapur"],
  "Dolakha": ["Bhimeshwar", "Jiri"],
  "Dolpa": ["Thuli Bheri", "Tripurasundari"],
  "Doti": ["Dipayal Silgadhi", "Shikhar"],
  "Eastern Rukum": ["Sisne", "Bhume", "Putha Uttarganga"],
  "Gorkha": ["Gorkha", "Palungtar"],
  "Gulmi": ["Resunga", "Musikot"],
  "Humla": ["Simikot", "Namkha", "Kharpunath", "Sarkegad", "Chankheli", "Adanchuli", "Tanjakot"],
  "Ilam": ["Ilam", "Deumai", "Mai", "Suryodaya"],
  "Jajarkot": ["Khalanga", "Bheri", "Chhedagad", "Nalgad"],
  "Jhapa": ["Bhadrapur", "Birtamode", "Damak", "Mechinagar", "Kankai", "Arjundhara", "Shivasatakshi", "Gauradaha"],
  "Jumla": ["Chandannath"],
  "Kailali": ["Dhangadhi", "Tikapur", "Ghodaghodi", "Lamki Chuha", "Bhajani", "Godawari", "Gauriganga"],
  "Kalikot": ["Khandachakra", "Raskot", "Tilagupha"],
  "Kanchanpur": ["Bhimdatta", "Punarbas", "Krishnapur", "Mahakali", "Shuklaphanta", "Belauri", "Bedkot"],
  "Kapilvastu": ["Kapilvastu", "Banganga", "Buddhabhumi", "Shivaraj", "Krishnanagar", "Maharajganj"],
  "Kaski": ["Pokhara"],
  "Kathmandu": ["Kathmandu", "Kirtipur", "Gokarneshwor", "Chandragiri", "Tokha", "Tarakeshwar", "Nagarjun", "Budhanilkantha", "Shankharapur", "Kageshwori Manohara", "Dakshinkali"],
  "Kavrepalanchok": ["Dhulikhel", "Banepa", "Panauti", "Panchkhal", "Namo Buddha", "Mandandeupur"],
  "Khotang": ["Diktel Rupakot Majhuwagadhi", "Halesi Tuwachung"],
  "Lalitpur": ["Lalitpur", "Godawari", "Mahalaxmi"],
  "Lamjung": ["Besisahar", "Sundarbazar", "Rainas", "Madhya Nepal"],
  "Mahottari": ["Jaleshwar", "Bardibas", "Gaushala", "Aurahi", "Bhangaha", "Matihani", "Loharpatti", "Ramgopalpur", "Balawa", "Manra Shiswa"],
  "Makwanpur": ["Hetauda", "Thaha"],
  "Manang": ["Chame", "Nason", "Narpa Bhumi", "Manang Ngisyang"],
  "Morang": ["Biratnagar", "Belbari", "Letang", "Pathari Sanischare", "Ratuwamai", "Sunawarshi", "Uralabari"],
  "Mugu": ["Chhayanath Rara"],
  "Mustang": ["Jomsom", "Gharapjhong", "Thasang", "Lomanthang", "Lo-Ghekar Damodarkunda", "Baragung Muktichhetra"],
  "Myagdi": ["Beni"],
  "Nawalpur": ["Kawasoti", "Gaindakot", "Devchuli", "Madhyabindu"],
  "Nuwakot": ["Bidur", "Belkotgadhi"],
  "Okhaldhunga": ["Siddhicharan"],
  "Palpa": ["Tansen", "Rampur"],
  "Panchthar": ["Phidim"],
  "Parasi": ["Ramgram", "Sunwal", "Bardaghat"],
  "Parbat": ["Kushma", "Phalebas"],
  "Parsa": ["Birgunj", "Bahudarmai", "Parsagadhi", "Pokhariya"],
  "Pyuthan": ["Pyuthan", "Swargadwari"],
  "Ramechhap": ["Manthali", "Ramechhap"],
  "Rasuwa": ["Dhunche", "Gosaikunda", "Kalika", "Naukunda", "Parvatikunda", "Uttargaya"],
  "Rautahat": ["Gaur", "Chandrapur", "Garuda", "Baudhimai", "Brindaban", "Dewahi Gonahi", "Gadhimai", "Gujara", "Ishanath", "Katahariya", "Madhav Narayan", "Maulapur", "Paroha", "Phatuwa Bijayapur", "Rajdevi", "Rajpur"],
  "Rolpa": ["Rolpa"],
  "Rupandehi": ["Butwal", "Siddharthanagar", "Devdaha", "Lumbini Sanskritik", "Sainamaina", "Tilottama"],
  "Salyan": ["Shaarda", "Bagchaur", "Bangad Kupinde"],
  "Sankhuwasabha": ["Khandbari", "Chainpur", "Dharmadevi", "Madi", "Panchkhapan"],
  "Saptari": ["Rajbiraj", "Kanchanrup", "Dakneshwori", "Bodebarsain", "Khadak", "Shambhunath", "Surunga", "Hanumannagar Kankalini", "Saptakoshi"],
  "Sarlahi": ["Malangwa", "Hariwan", "Lalbandi", "Ishworpur", "Barahathwa", "Bagmati", "Balara", "Godaita", "Haripur", "Haripurwa", "Kabilasi"],
  "Sindhuli": ["Kamalamai", "Dudhauli"],
  "Sindhupalchok": ["Chautara SangachokGadhi", "Bahrabise", "Melamchi"],
  "Siraha": ["Siraha", "Lahan", "Dhangadhimai", "Golbazar", "Mirchaiya", "Kalyanpur", "Karjanha", "Sukhipur"],
  "Solukhumbu": ["Solududhkunda"],
  "Sunsari": ["Itahari", "Dharan", "Inaruwa", "Duhabi", "Ramdhuni", "Barahachhetra"],
  "Surkhet": ["Birendranagar", "Bheriganga", "Gurbhakot", "Panchapuri", "Lekbeshi"],
  "Syangja": ["Putalibazar", "Waling", "Chapakot", "Bhirkot", "Galyang"],
  "Tanahun": ["Vyas", "Bhanu", "Bhimad", "Shuklagandaki"],
  "Taplejung": ["Phungling"],
  "Terhathum": ["Myanglung", "Laligurans"],
  "Udayapur": ["Triyuga", "Chaudandigadhi", "Belaka", "Katari"],
  "Western Rukum": ["Musikot", "Chaurjahari", "Aathbiskot"]
};
